### ISSUE TITLE
Long Loading Times?

### ISSUE THREAD

**Issue by sulkhanp** [Parth/dotfiles#43] opened 2018-07-12 09:52 UTC
Hi. I'm using WSL on Windows. I noticed that zsh takes relatively more time to load than bash. Is this because of the dotfiles? 
```
[~, 12s]: time zsh -i -c exit
Updating configuration
zsh -i -c exit  0.06s user 0.38s system 44% cpu 0.977 total
```
Report says 0.977 sec total, but I think I'm watching `Updating configuration` like 3 seconds on start-up.

I read that oh-my-zsh is to blame for bad zsh performance.

**Comment by Parth** [comment] 2018-07-15 16:43
I also used WSL for a while. I believe this is the root cause: 

https://github.com/Microsoft/WSL/issues/981

So it seems like file io on structures like the one git uses is very slow. There's a few interesting things i messed around with at the time, including making WSL use git.exe rather than ubuntu's git. I can't remember the specifics of that experiment, but iirc it was a struggle to do things with ssh keys. 

If I were still using a windows machine for dev, I think I would experiment more on the side of VMs with shared volumes. My intuition says that long term this would be more stable, and the overhead is probably not that bad if you use a lightweight vm like ubuntu server.

Was also thinking about experimenting with a docker type container for dev, but haven't fully thought through the specifics of that.

Better windows support is definitely something I'm interested in, so please do continue the conversation below, but since there's nothing actionable at the moment for me to do I'll close this.

**Closed by Parth** 2018-07-15 16:43 UTC

**Comment by Parth** [comment] 2018-07-16 15:18
Like I mentioned, when I experimented with these workarounds I had trouble using things like ssh-keys and ended up abandoning it. 

Furthermore this is somewhat specific to windows, so I didn't end up adding it to this repository.

If you wanted to:
1. fork this repository
2. [detect if someone is running WSL](https://stackoverflow.com/questions/38859145/detect-ubuntu-on-windows-vs-native-ubuntu-from-bash-script)
3. check if they have git.exe instead of normal git
4. apply the workaround presented in that issue

I'd be happy to accept that pull request.
